name: Announce Latest Nightly to Discord

on:
  workflow_call:

  workflow_dispatch:
    inputs:
      diagnostic_mode:
        description: Diagnostic Mode
        type: boolean
        default: false
        required: true

jobs:
  vars:
    name: Get Variables
    runs-on: ubuntu-22.04
    outputs:
      mcVersion: ${{steps.gradle_props.outputs.minecraft_version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Read MC and Forge versions
        id: gradle_props
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "gradle.properties"
          properties: "minecraft_version"

  get-package-info:
    name: Get Latest Package Info
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.download-info.outputs.version }}
    steps:
      - name: Download Package Info
        id: download-info
        uses: compactmods/dl-package-info@1.0.3
        env:
          GQL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: compactmods
          repo: simplehoney
          group: dev.compactmods.simplehoney.simplehoney-neoforge
          filter: "^simplehoney-neoforge-(?:[\\d\\.]+)-nightly.jar$"
          outputFile: simplehoney-nightly.json

      - name: Debug output
        run: |
          echo "Version: ${{ steps.download-info.outputs.version }}"
          cat simplehoney-nightly.json

      - name: Read info into variable [latest]
        id: info
        run: echo "latestJson=$(cat simplehoney-nightly.json)" >> $GITHUB_OUTPUT

      - name: Download JAR and prepare artifacts
        run: |
          mkdir release
          curl -L "${{ fromJson(steps.info.outputs.latestJson)[0].url }}" -o "release/${{ fromJson(steps.info.outputs.latestJson)[0].name}}"
          mv simplehoney-nightly.json release/simplehoney-nightly.json

      - name: Add Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release

  announce:
    name: Discord Announcement
    needs: [ vars, get-package-info ]
    runs-on: ubuntu-22.04
    steps:
      - name: Grab JAR and Info
        uses: actions/download-artifact@v4
        with:
          name: release
          path: .

      - name: Read info into variable [latest]
        id: info
        run: echo "latestJson=$(cat simplehoney-nightly.json)" >> $GITHUB_OUTPUT

      - name: Announce Timestamp
        id: timestamp
        run: echo "buildTimestamp=$(date --iso-8601)" >> $GITHUB_OUTPUT

      - name: Announce Release
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_NIGHTLY_WEBHOOK }}
          avatar-url: "https://compactmods.dev/personal-shrinking-device.png"
          content: "**New Version Available: Simple Honey v${{ needs.get-package-info.outputs.version }}"
          filename: ${{ fromJson(steps.info.outputs.latestJson)[0].name }}
          embed-title: "**Mod File Information**"
          embed-description: "Filename: ${{ fromJson(steps.info.outputs.latestJson)[0].name}}"
          embed-url: "https://www.curseforge.com/minecraft/mc-mods/simple-honey"
          embed-thumbnail-url: "https://media.forgecdn.net/avatars/thumbnails/973/13/64/64/638475522072947924.png"
          embed-timestamp: ${{ steps.timestamp.outputs.buildTimestamp }}
