name: Publish and Announce Nightly Build

env:
  GH_PKG_URL: "https://maven.pkg.github.com/${{ github.repository }}"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/**/*"

jobs:
  vars:
    name: Get Variables
    runs-on: ubuntu-22.04
    outputs:
      version: ${{steps.version.outputs.version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 150
          fetch-tags: true
          submodules: true
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          change_path: "neoforge"
          version_format: "${major}.${minor}.${patch}.${increment}-nightly"
          search_commit_body: true

  datagen:
    needs: [vars]
    uses: ./.github/workflows/datagen.yml
    secrets: inherit
    with:
      version: ${{ needs.vars.outputs.version }}

  publish:
    needs: [vars, datagen]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      version: ${{ needs.vars.outputs.version }}

  announce:
    name: Discord Announcement
    needs: [ publish ]
    uses: ./.github/workflows/announce-latest-nightly.yml
    secrets: inherit